package uk.gov.justice.digital.hmpps.hmppsidentifyremandperiodsapi.relevantremand.model

enum class LegacyDataProblemType {
  MISSING_OFFENCE_DATE,
  MISSING_COURT_OUTCOME,
  UNSUPPORTED_OUTCOME,
  RELEASE_DATE_CALCULATION,
  MISSING_RECALL_EVENT,
  RECALL_EVENT_ON_SENTENCE_DATE,
  MISSING_COURT_EVENT_FOR_IMPRISONMENT_STATUS_REMAND,
  MISSING_COURT_EVENT_FOR_IMPRISONMENT_STATUS_RECALL,
  MISSING_COURT_EVENT_FOR_IMPRISONMENT_STATUS_SENTENCING,
  MISSING_STOP_EVENT,
  START_EVENT_ON_SENTENCE_DATE,
}
