---
# Per environment values which override defaults in hmpps-identify-remand-periods-api/values.yaml

generic-service:
  ingress:
    host: identify-remand-periods-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search.prison.service.justice.gov.uk
    ADJUSTMENTS_API_URL: https://adjustments-api.hmpps.service.justice.gov.uk
    CALCULATERELEASEDATES_API_URL: https://calculate-release-dates-api.hmpps.service.justice.gov.uk
    PRIMARY_RELEASE_DATE_PROVIDER: HISTORIC

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
